version: '3.7'

services:

  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    container_name: gateway-lodas
    ports:
      - 8080:8080

  lodas:
    build:
      context: backend/lodas
      dockerfile: Dockerfile
    container_name: lodas-service
    depends_on:
      - lodas_db
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: lodas_db
      DB_PORT: 3306
      DB_NAME: lodas

  auth:
    build:
      context: backend/auth
      dockerfile: Dockerfile
    container_name: auth-lodas
    volumes:
      - ./backend/auth:/app
    depends_on:
      - lodas_db
      - redis
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: lodas_db
      DB_PORT: 3306
      DB_NAME: lodas
      CACHE_HOST: redis
      CACHE_PORT: 6379
      CACHE_PASSWORD: ""
      CACHE_DB: 0

  lodas_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: lodas
    container_name: 'db-lodas'
    volumes:
      - "./tmp/db/lodas:/var/lib/mysql"
    ports:
      - 33306:3306

  redis:
    image: redis:latest
    container_name: redis-lodas
    ports:
      - "6379:6379"
    # restart: always
