// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/betsetting"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/predicate"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/sheet"
)

// BetSettingQuery is the builder for querying BetSetting entities.
type BetSettingQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.BetSetting
	withSheets *SheetQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BetSettingQuery builder.
func (bsq *BetSettingQuery) Where(ps ...predicate.BetSetting) *BetSettingQuery {
	bsq.predicates = append(bsq.predicates, ps...)
	return bsq
}

// Limit the number of records to be returned by this query.
func (bsq *BetSettingQuery) Limit(limit int) *BetSettingQuery {
	bsq.ctx.Limit = &limit
	return bsq
}

// Offset to start from.
func (bsq *BetSettingQuery) Offset(offset int) *BetSettingQuery {
	bsq.ctx.Offset = &offset
	return bsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bsq *BetSettingQuery) Unique(unique bool) *BetSettingQuery {
	bsq.ctx.Unique = &unique
	return bsq
}

// Order specifies how the records should be ordered.
func (bsq *BetSettingQuery) Order(o ...OrderFunc) *BetSettingQuery {
	bsq.order = append(bsq.order, o...)
	return bsq
}

// QuerySheets chains the current query on the "sheets" edge.
func (bsq *BetSettingQuery) QuerySheets() *SheetQuery {
	query := (&SheetClient{config: bsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(betsetting.Table, betsetting.FieldID, selector),
			sqlgraph.To(sheet.Table, sheet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, betsetting.SheetsTable, betsetting.SheetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BetSetting entity from the query.
// Returns a *NotFoundError when no BetSetting was found.
func (bsq *BetSettingQuery) First(ctx context.Context) (*BetSetting, error) {
	nodes, err := bsq.Limit(1).All(setContextOp(ctx, bsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{betsetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bsq *BetSettingQuery) FirstX(ctx context.Context) *BetSetting {
	node, err := bsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BetSetting ID from the query.
// Returns a *NotFoundError when no BetSetting ID was found.
func (bsq *BetSettingQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = bsq.Limit(1).IDs(setContextOp(ctx, bsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{betsetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bsq *BetSettingQuery) FirstIDX(ctx context.Context) int64 {
	id, err := bsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BetSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BetSetting entity is found.
// Returns a *NotFoundError when no BetSetting entities are found.
func (bsq *BetSettingQuery) Only(ctx context.Context) (*BetSetting, error) {
	nodes, err := bsq.Limit(2).All(setContextOp(ctx, bsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{betsetting.Label}
	default:
		return nil, &NotSingularError{betsetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bsq *BetSettingQuery) OnlyX(ctx context.Context) *BetSetting {
	node, err := bsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BetSetting ID in the query.
// Returns a *NotSingularError when more than one BetSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (bsq *BetSettingQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = bsq.Limit(2).IDs(setContextOp(ctx, bsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{betsetting.Label}
	default:
		err = &NotSingularError{betsetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bsq *BetSettingQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := bsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BetSettings.
func (bsq *BetSettingQuery) All(ctx context.Context) ([]*BetSetting, error) {
	ctx = setContextOp(ctx, bsq.ctx, "All")
	if err := bsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BetSetting, *BetSettingQuery]()
	return withInterceptors[[]*BetSetting](ctx, bsq, qr, bsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bsq *BetSettingQuery) AllX(ctx context.Context) []*BetSetting {
	nodes, err := bsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BetSetting IDs.
func (bsq *BetSettingQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	ctx = setContextOp(ctx, bsq.ctx, "IDs")
	if err := bsq.Select(betsetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bsq *BetSettingQuery) IDsX(ctx context.Context) []int64 {
	ids, err := bsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bsq *BetSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bsq.ctx, "Count")
	if err := bsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bsq, querierCount[*BetSettingQuery](), bsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bsq *BetSettingQuery) CountX(ctx context.Context) int {
	count, err := bsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bsq *BetSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bsq.ctx, "Exist")
	switch _, err := bsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bsq *BetSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := bsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BetSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bsq *BetSettingQuery) Clone() *BetSettingQuery {
	if bsq == nil {
		return nil
	}
	return &BetSettingQuery{
		config:     bsq.config,
		ctx:        bsq.ctx.Clone(),
		order:      append([]OrderFunc{}, bsq.order...),
		inters:     append([]Interceptor{}, bsq.inters...),
		predicates: append([]predicate.BetSetting{}, bsq.predicates...),
		withSheets: bsq.withSheets.Clone(),
		// clone intermediate query.
		sql:  bsq.sql.Clone(),
		path: bsq.path,
	}
}

// WithSheets tells the query-builder to eager-load the nodes that are connected to
// the "sheets" edge. The optional arguments are used to configure the query builder of the edge.
func (bsq *BetSettingQuery) WithSheets(opts ...func(*SheetQuery)) *BetSettingQuery {
	query := (&SheetClient{config: bsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bsq.withSheets = query
	return bsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Values *schema.BetSettingMap `json:"values,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BetSetting.Query().
//		GroupBy(betsetting.FieldValues).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (bsq *BetSettingQuery) GroupBy(field string, fields ...string) *BetSettingGroupBy {
	bsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BetSettingGroupBy{build: bsq}
	grbuild.flds = &bsq.ctx.Fields
	grbuild.label = betsetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Values *schema.BetSettingMap `json:"values,omitempty"`
//	}
//
//	client.BetSetting.Query().
//		Select(betsetting.FieldValues).
//		Scan(ctx, &v)
//
func (bsq *BetSettingQuery) Select(fields ...string) *BetSettingSelect {
	bsq.ctx.Fields = append(bsq.ctx.Fields, fields...)
	sbuild := &BetSettingSelect{BetSettingQuery: bsq}
	sbuild.label = betsetting.Label
	sbuild.flds, sbuild.scan = &bsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BetSettingSelect configured with the given aggregations.
func (bsq *BetSettingQuery) Aggregate(fns ...AggregateFunc) *BetSettingSelect {
	return bsq.Select().Aggregate(fns...)
}

func (bsq *BetSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bsq); err != nil {
				return err
			}
		}
	}
	for _, f := range bsq.ctx.Fields {
		if !betsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bsq.path != nil {
		prev, err := bsq.path(ctx)
		if err != nil {
			return err
		}
		bsq.sql = prev
	}
	return nil
}

func (bsq *BetSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BetSetting, error) {
	var (
		nodes       = []*BetSetting{}
		_spec       = bsq.querySpec()
		loadedTypes = [1]bool{
			bsq.withSheets != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BetSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BetSetting{config: bsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bsq.withSheets; query != nil {
		if err := bsq.loadSheets(ctx, query, nodes,
			func(n *BetSetting) { n.Edges.Sheets = []*Sheet{} },
			func(n *BetSetting, e *Sheet) { n.Edges.Sheets = append(n.Edges.Sheets, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bsq *BetSettingQuery) loadSheets(ctx context.Context, query *SheetQuery, nodes []*BetSetting, init func(*BetSetting), assign func(*BetSetting, *Sheet)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*BetSetting)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Sheet(func(s *sql.Selector) {
		s.Where(sql.InValues(betsetting.SheetsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.bet_setting_sheets
		if fk == nil {
			return fmt.Errorf(`foreign-key "bet_setting_sheets" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bet_setting_sheets" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bsq *BetSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bsq.querySpec()
	_spec.Node.Columns = bsq.ctx.Fields
	if len(bsq.ctx.Fields) > 0 {
		_spec.Unique = bsq.ctx.Unique != nil && *bsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bsq.driver, _spec)
}

func (bsq *BetSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   betsetting.Table,
			Columns: betsetting.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: betsetting.FieldID,
			},
		},
		From:   bsq.sql,
		Unique: true,
	}
	if unique := bsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := bsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, betsetting.FieldID)
		for i := range fields {
			if fields[i] != betsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bsq *BetSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bsq.driver.Dialect())
	t1 := builder.Table(betsetting.Table)
	columns := bsq.ctx.Fields
	if len(columns) == 0 {
		columns = betsetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bsq.sql != nil {
		selector = bsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bsq.ctx.Unique != nil && *bsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bsq.predicates {
		p(selector)
	}
	for _, p := range bsq.order {
		p(selector)
	}
	if offset := bsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BetSettingGroupBy is the group-by builder for BetSetting entities.
type BetSettingGroupBy struct {
	selector
	build *BetSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bsgb *BetSettingGroupBy) Aggregate(fns ...AggregateFunc) *BetSettingGroupBy {
	bsgb.fns = append(bsgb.fns, fns...)
	return bsgb
}

// Scan applies the selector query and scans the result into the given value.
func (bsgb *BetSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bsgb.build.ctx, "GroupBy")
	if err := bsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BetSettingQuery, *BetSettingGroupBy](ctx, bsgb.build, bsgb, bsgb.build.inters, v)
}

func (bsgb *BetSettingGroupBy) sqlScan(ctx context.Context, root *BetSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bsgb.fns))
	for _, fn := range bsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bsgb.flds)+len(bsgb.fns))
		for _, f := range *bsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BetSettingSelect is the builder for selecting fields of BetSetting entities.
type BetSettingSelect struct {
	*BetSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bss *BetSettingSelect) Aggregate(fns ...AggregateFunc) *BetSettingSelect {
	bss.fns = append(bss.fns, fns...)
	return bss
}

// Scan applies the selector query and scans the result into the given value.
func (bss *BetSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bss.ctx, "Select")
	if err := bss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BetSettingQuery, *BetSettingSelect](ctx, bss.BetSettingQuery, bss, bss.inters, v)
}

func (bss *BetSettingSelect) sqlScan(ctx context.Context, root *BetSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bss.fns))
	for _, fn := range bss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
