// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/manhrev/lodas/backend/lodas/pkg/ent/record"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/result"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/schema"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/sheet"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescBetType is the schema descriptor for bet_type field.
	recordDescBetType := recordFields[3].Descriptor()
	// record.DefaultBetType holds the default value on creation for the bet_type field.
	record.DefaultBetType = recordDescBetType.Default.(int64)
	resultFields := schema.Result{}.Fields()
	_ = resultFields
	// resultDescProvince is the schema descriptor for province field.
	resultDescProvince := resultFields[1].Descriptor()
	// result.DefaultProvince holds the default value on creation for the province field.
	result.DefaultProvince = resultDescProvince.Default.(int64)
	// resultDescCreatedTime is the schema descriptor for created_time field.
	resultDescCreatedTime := resultFields[2].Descriptor()
	// result.DefaultCreatedTime holds the default value on creation for the created_time field.
	result.DefaultCreatedTime = resultDescCreatedTime.Default.(time.Time)
	sheetFields := schema.Sheet{}.Fields()
	_ = sheetFields
	// sheetDescStatus is the schema descriptor for status field.
	sheetDescStatus := sheetFields[1].Descriptor()
	// sheet.DefaultStatus holds the default value on creation for the status field.
	sheet.DefaultStatus = sheetDescStatus.Default.(int64)
	// sheetDescArea is the schema descriptor for area field.
	sheetDescArea := sheetFields[3].Descriptor()
	// sheet.DefaultArea holds the default value on creation for the area field.
	sheet.DefaultArea = sheetDescArea.Default.(int64)
	// sheetDescProvince is the schema descriptor for province field.
	sheetDescProvince := sheetFields[4].Descriptor()
	// sheet.DefaultProvince holds the default value on creation for the province field.
	sheet.DefaultProvince = sheetDescProvince.Default.(int64)
	// sheetDescRatio is the schema descriptor for ratio field.
	sheetDescRatio := sheetFields[5].Descriptor()
	// sheet.DefaultRatio holds the default value on creation for the ratio field.
	sheet.DefaultRatio = sheetDescRatio.Default.(float64)
}
