// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/betsetting"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/predicate"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/record"
	"github.com/manhrev/lodas/backend/lodas/pkg/ent/sheet"
)

// SheetQuery is the builder for querying Sheet entities.
type SheetQuery struct {
	config
	ctx            *QueryContext
	order          []OrderFunc
	inters         []Interceptor
	predicates     []predicate.Sheet
	withRecords    *RecordQuery
	withBetSetting *BetSettingQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SheetQuery builder.
func (sq *SheetQuery) Where(ps ...predicate.Sheet) *SheetQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SheetQuery) Limit(limit int) *SheetQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SheetQuery) Offset(offset int) *SheetQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SheetQuery) Unique(unique bool) *SheetQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SheetQuery) Order(o ...OrderFunc) *SheetQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryRecords chains the current query on the "records" edge.
func (sq *SheetQuery) QueryRecords() *RecordQuery {
	query := (&RecordClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sheet.Table, sheet.FieldID, selector),
			sqlgraph.To(record.Table, record.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sheet.RecordsTable, sheet.RecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBetSetting chains the current query on the "bet_setting" edge.
func (sq *SheetQuery) QueryBetSetting() *BetSettingQuery {
	query := (&BetSettingClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sheet.Table, sheet.FieldID, selector),
			sqlgraph.To(betsetting.Table, betsetting.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sheet.BetSettingTable, sheet.BetSettingColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Sheet entity from the query.
// Returns a *NotFoundError when no Sheet was found.
func (sq *SheetQuery) First(ctx context.Context) (*Sheet, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sheet.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SheetQuery) FirstX(ctx context.Context) *Sheet {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Sheet ID from the query.
// Returns a *NotFoundError when no Sheet ID was found.
func (sq *SheetQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sheet.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SheetQuery) FirstIDX(ctx context.Context) int64 {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Sheet entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Sheet entity is found.
// Returns a *NotFoundError when no Sheet entities are found.
func (sq *SheetQuery) Only(ctx context.Context) (*Sheet, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sheet.Label}
	default:
		return nil, &NotSingularError{sheet.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SheetQuery) OnlyX(ctx context.Context) *Sheet {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Sheet ID in the query.
// Returns a *NotSingularError when more than one Sheet ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SheetQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sheet.Label}
	default:
		err = &NotSingularError{sheet.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SheetQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Sheets.
func (sq *SheetQuery) All(ctx context.Context) ([]*Sheet, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Sheet, *SheetQuery]()
	return withInterceptors[[]*Sheet](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SheetQuery) AllX(ctx context.Context) []*Sheet {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Sheet IDs.
func (sq *SheetQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err := sq.Select(sheet.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SheetQuery) IDsX(ctx context.Context) []int64 {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SheetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SheetQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SheetQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SheetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SheetQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SheetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SheetQuery) Clone() *SheetQuery {
	if sq == nil {
		return nil
	}
	return &SheetQuery{
		config:         sq.config,
		ctx:            sq.ctx.Clone(),
		order:          append([]OrderFunc{}, sq.order...),
		inters:         append([]Interceptor{}, sq.inters...),
		predicates:     append([]predicate.Sheet{}, sq.predicates...),
		withRecords:    sq.withRecords.Clone(),
		withBetSetting: sq.withBetSetting.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithRecords tells the query-builder to eager-load the nodes that are connected to
// the "records" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SheetQuery) WithRecords(opts ...func(*RecordQuery)) *SheetQuery {
	query := (&RecordClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withRecords = query
	return sq
}

// WithBetSetting tells the query-builder to eager-load the nodes that are connected to
// the "bet_setting" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SheetQuery) WithBetSetting(opts ...func(*BetSettingQuery)) *SheetQuery {
	query := (&BetSettingClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withBetSetting = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status int64 `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Sheet.Query().
//		GroupBy(sheet.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sq *SheetQuery) GroupBy(field string, fields ...string) *SheetGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SheetGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = sheet.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status int64 `json:"status,omitempty"`
//	}
//
//	client.Sheet.Query().
//		Select(sheet.FieldStatus).
//		Scan(ctx, &v)
//
func (sq *SheetQuery) Select(fields ...string) *SheetSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SheetSelect{SheetQuery: sq}
	sbuild.label = sheet.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SheetSelect configured with the given aggregations.
func (sq *SheetQuery) Aggregate(fns ...AggregateFunc) *SheetSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SheetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !sheet.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SheetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Sheet, error) {
	var (
		nodes       = []*Sheet{}
		withFKs     = sq.withFKs
		_spec       = sq.querySpec()
		loadedTypes = [2]bool{
			sq.withRecords != nil,
			sq.withBetSetting != nil,
		}
	)
	if sq.withBetSetting != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, sheet.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Sheet).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Sheet{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withRecords; query != nil {
		if err := sq.loadRecords(ctx, query, nodes,
			func(n *Sheet) { n.Edges.Records = []*Record{} },
			func(n *Sheet, e *Record) { n.Edges.Records = append(n.Edges.Records, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withBetSetting; query != nil {
		if err := sq.loadBetSetting(ctx, query, nodes, nil,
			func(n *Sheet, e *BetSetting) { n.Edges.BetSetting = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SheetQuery) loadRecords(ctx context.Context, query *RecordQuery, nodes []*Sheet, init func(*Sheet), assign func(*Sheet, *Record)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Sheet)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Record(func(s *sql.Selector) {
		s.Where(sql.InValues(sheet.RecordsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sheet_records
		if fk == nil {
			return fmt.Errorf(`foreign-key "sheet_records" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sheet_records" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SheetQuery) loadBetSetting(ctx context.Context, query *BetSettingQuery, nodes []*Sheet, init func(*Sheet), assign func(*Sheet, *BetSetting)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Sheet)
	for i := range nodes {
		if nodes[i].bet_setting_sheets == nil {
			continue
		}
		fk := *nodes[i].bet_setting_sheets
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(betsetting.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bet_setting_sheets" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *SheetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SheetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sheet.Table,
			Columns: sheet.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: sheet.FieldID,
			},
		},
		From:   sq.sql,
		Unique: true,
	}
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sheet.FieldID)
		for i := range fields {
			if fields[i] != sheet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SheetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(sheet.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = sheet.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SheetGroupBy is the group-by builder for Sheet entities.
type SheetGroupBy struct {
	selector
	build *SheetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SheetGroupBy) Aggregate(fns ...AggregateFunc) *SheetGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SheetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SheetQuery, *SheetGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SheetGroupBy) sqlScan(ctx context.Context, root *SheetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SheetSelect is the builder for selecting fields of Sheet entities.
type SheetSelect struct {
	*SheetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SheetSelect) Aggregate(fns ...AggregateFunc) *SheetSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SheetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SheetQuery, *SheetSelect](ctx, ss.SheetQuery, ss, ss.inters, v)
}

func (ss *SheetSelect) sqlScan(ctx context.Context, root *SheetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
