database:
  username: "root"
  password: "password@1"
  domain: "lodas_db"
  port: "3306"
  name: "lodas"

grpc:
  host: "0.0.0.0"
  port: "8080"
  network: "tcp"

cache:
  host: "redis"
  port: "6379"
  password: ""
  db: 0
