// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BetSetting is the predicate function for betsetting builders.
type BetSetting func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// Result is the predicate function for result builders.
type Result func(*sql.Selector)

// Sheet is the predicate function for sheet builders.
type Sheet func(*sql.Selector)
